### ISSUE TITLE
Forgot run `npm run prepublish` before pulish branch koa@2?

### ISSUE THREAD

**Issue by malash** [kilianc/koa-jsonp#8]
Forgot run `npm run prepublish` before pulish branch `koa@2`?

`Error: Cannot find module './dist/jsonp'`

**Comment by kilianc** [comment]
Hey @malash thanks for giving this module a try. `pre-publish` is a hook it's run by npm itself. What version are you using?

**Comment by kilianc** [comment]
@malash I was ignoring `dist` and npm publish ignores it as well if it doesn't have its own `.npmignore`. it should be fine now.

Thanks so much for taking the time to report this
